/// In-memory simulator helpers for DCS development and tests.
library;

import 'package:dcs_common/dcs_common.dart';
import 'package:dcs_host/dcs_host.dart';

class SimulatedDcsDevice {
  SimulatedDcsDevice({
    required this.component,
    DcsRuntimeState initialState = DcsRuntimeState.configured,
  }) : status = DcsRuntimeStatus.now(
         component: component,
         state: initialState,
         message: 'Simulated device initialized.',
       );

  final DcsRuntimeComponent component;
  DcsRuntimeStatus status;

  void setState(DcsRuntimeState state, String message) {
    status = DcsRuntimeStatus.now(
      component: component,
      state: state,
      message: message,
    );
  }
}

class SimulatedHostAdapter implements DcsHostAdapter {
  SimulatedHostAdapter({this.responses = const {}});

  final Map<DcsHostMessageType, String> responses;

  @override
  DcsTransportKind get transport => DcsTransportKind.simulator;

  @override
  Future<DcsHostResponse> send(DcsHostRequest request) async {
    return DcsHostResponse(
      requestId: request.id,
      ok: true,
      payload: responses[request.type] ?? 'SIMULATED OK',
      code: 'SIM',
      message: 'Response generated by dcs_simulator.',
    );
  }
}
